name: ZeroMQInterface
version: 0.6
date: 21/08/2017
description: |
    ZeroMQ bindings for GAP

authors:
    - name: Markus Pfeiffer
      url: http://www.morphism.de/~markusp/
    - name: Reimer Behrends
      url: http://www.mathematik.uni-kl.de/agag/mitglieder/wissenschaftliche-mitarbeiter/dr-reimer-behrends/

maintainers:
    - name: Markus Pfeiffer
      url: http://www.morphism.de/~markusp/

GAP: ">= 4.9"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/ZeroMQInterface/
readme: README
packageinfo: https://gap-packages.github.io/ZeroMQInterface/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/ZeroMQInterface/releases/download/v0.6/ZeroMQInterface-0.6.tar.gz

abstract: |
    

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
