name: ZeroMQInterface
version: "0.15"
license: "GPL-2.0-or-later"
date: 2024-07-01
description: |
    ZeroMQ bindings for GAP

authors:
    - name: Markus Pfeiffer
      url: http://www.morphism.de/~markusp/
    - name: Reimer Behrends
      url: http://www.mathematik.uni-kl.de/agag/mitglieder/wissenschaftliche-mitarbeiter/dr-reimer-behrends/

maintainers:
    - name: The GAP Team
      url: mailto:support@gap-system.org

GAP: ">= 4.9"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.6.1"
      url: "https://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/ZeroMQInterface/
readme: README.md
packageinfo: https://gap-packages.github.io/ZeroMQInterface/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/ZeroMQInterface/releases/download/v0.15/ZeroMQInterface-0.15.tar.gz

abstract: |

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    zeromq, messaging, distributed.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>PBT24</span>]   <b class='BibAuthor'>Pfeiffer, M., Behrends, R. and GAP Team, T.</b>,
     <i class='BibTitle'>ZeroMQInterface, ZeroMQ bindings for GAP,
             Version 0.15</i>
     (<span class='BibYear'>2024</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/ZeroMQInterface/">https://gap-packages.github.io/ZeroMQInterface/</a></span>.
    </p>
    

bibtex: |
    @misc{ ZeroMQInterface,
      author =           {Pfeiffer, M. and Behrends, R. and GAP Team, T.},
      title =            {{ZeroMQInterface},  ZeroMQ bindings for GAP, {V}ersion
                          0.15},
      month =            {Jul},
      year =             {2024},
      note =             {GAP package},
      howpublished =     {\href
                          {https://gap-packages.github.io/ZeroMQInterface/}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{ZeroMQInterface/}}},
      keywords =         {zeromq; messaging; distributed},
      printedkey =       {PBT24}
    }

